// <auto-generated />
using System;
using MIS_DEMO.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MIS_DEMO.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MIS_DEMO.Models.AppLink", b =>
                {
                    b.Property<string>("LinkName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LinkName");

                    b.ToTable("LINKS");
                });

            modelBuilder.Entity("MIS_DEMO.Models.Cheque", b =>
                {
                    b.Property<string>("ChequeRefNO")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BankCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChequeNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ChequeRefDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChequeStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChequeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Cr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Deposit_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Deposit_Ref")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Dr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Origin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OwnerCode");

                    b.Property<string>("OwnerType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RealizedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Realized_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceiptVoucherNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ReceiptVoucherNo");

                    b.Property<DateTime?>("Returned_Date")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("isRealized")
                        .HasColumnType("bit");

                    b.HasKey("ChequeRefNO");

                    b.ToTable("CHEQUE");
                });

            modelBuilder.Entity("MIS_DEMO.Models.CusCategory", b =>
                {
                    b.Property<string>("CusCategoryCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CusCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CusCategoryCode");

                    b.ToTable("CUS_CATEGORY");
                });

            modelBuilder.Entity("MIS_DEMO.Models.CustomerInvoiceMain", b =>
                {
                    b.Property<string>("InvoDocNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ComCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LocCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Cancel")
                        .HasColumnType("bit");

                    b.Property<int?>("CreditDays")
                        .HasColumnType("int");

                    b.Property<string>("CusCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InvoiceAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Pat_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SalesRepCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isFinalDelivery")
                        .HasColumnType("bit");

                    b.HasKey("InvoDocNo", "ComCode", "LocCode");

                    b.ToTable("CUSTOMER_INVOICE_MAIN");
                });

            modelBuilder.Entity("MIS_DEMO.Models.CustomerOutstanding", b =>
                {
                    b.Property<decimal>("BalanceAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Bill_Com_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CusCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DuePayDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InvoiceAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LocCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManualNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ReturnAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("isExcelUpload")
                        .HasColumnType("bit");

                    b.Property<bool?>("isSystmUpload")
                        .HasColumnType("bit");

                    b.ToTable("CUSTOMER_OUTSTANDING");
                });

            modelBuilder.Entity("MIS_DEMO.Models.CustomerPayment", b =>
                {
                    b.Property<bool?>("Cancel")
                        .HasColumnType("bit");

                    b.Property<string>("CardRefNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChequeRefNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CusCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CusCode");

                    b.Property<string>("DocNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PayAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PayDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiptNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ReturnAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("CUSTOMER_PAYMENT");
                });

            modelBuilder.Entity("MIS_DEMO.Models.CustomerPaymentTemp", b =>
                {
                    b.Property<bool?>("Cancel")
                        .HasColumnType("bit");

                    b.Property<string>("CardRefNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChequeRefNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CusCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Method")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PayAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PayDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PayType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiptNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isDeposited")
                        .HasColumnType("bit");

                    b.ToTable("CUSTOMER_PAYMENT_TEMP");
                });

            modelBuilder.Entity("MIS_DEMO.Models.DirSupMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SupCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserNameDir")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DIR_SUP_MAP");
                });

            modelBuilder.Entity("MIS_DEMO.Models.DirTeamMap", b =>
                {
                    b.Property<string>("TeamCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserNameDir")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("DIR_TEAM_MAP");
                });

            modelBuilder.Entity("MIS_DEMO.Models.ExpenseMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DocumentPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpenseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TranNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExpenseMaster");
                });

            modelBuilder.Entity("MIS_DEMO.Models.ITEM_PRICE", b =>
                {
                    b.Property<decimal>("DiscountRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ItemRefNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("M_Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("S_Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("ITEM_PRICE");
                });

            modelBuilder.Entity("MIS_DEMO.Models.LoginLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.ToTable("LOGIN_LOGS");
                });

            modelBuilder.Entity("MIS_DEMO.Models.MasCreditType", b =>
                {
                    b.Property<int>("credittypeky")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("credittypeky"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdatetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("creditdays")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("inactive")
                        .HasColumnType("bit");

                    b.Property<string>("remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sessionid")
                        .HasColumnType("int");

                    b.Property<DateTime>("updatedatetime")
                        .HasColumnType("datetime2");

                    b.HasKey("credittypeky");

                    b.ToTable("mascredittype");
                });

            modelBuilder.Entity("MIS_DEMO.Models.MisDefaultConfig", b =>
                {
                    b.Property<int?>("AgingDefaultDays")
                        .HasColumnType("int");

                    b.Property<string>("CollectionFreeze")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CollectionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NonDelDefDays")
                        .HasColumnType("int");

                    b.Property<string>("OutstandInvType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdCheq")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("MIS_DEFAULT_CONFIG");
                });

            modelBuilder.Entity("MIS_DEMO.Models.NonDeliveredDays", b =>
                {
                    b.Property<int>("Days")
                        .HasColumnType("int")
                        .HasColumnName("Days");

                    b.ToTable("NON_DELIVERED_DAYS");
                });

            modelBuilder.Entity("MIS_DEMO.Models.OutstandingDays", b =>
                {
                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.ToTable("OUTSTANDING_DAYS");
                });

            modelBuilder.Entity("MIS_DEMO.Models.PartnerDetails", b =>
                {
                    b.Property<string>("Pcode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AltCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Area")
                        .HasColumnType("int");

                    b.Property<decimal>("AvaPoint")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BRNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPersonDesig")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPersonMob")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CreditLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreditPeriod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CusCategoryCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustCat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DOW")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaxNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntroBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IntroDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompanyCCUser")
                        .HasColumnType("bit");

                    b.Property<bool>("IsParentUser")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsUpload")
                        .HasColumnType("bit");

                    b.Property<string>("KeyParentPcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoyaltyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MaxSaleslimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Merital")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NICno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NoMembers")
                        .HasColumnType("int");

                    b.Property<string>("ParentPcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PointPrecntage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TelNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Web")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("availabledispoint")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("confirm")
                        .HasColumnType("bit");

                    b.Property<bool?>("isNonTrading")
                        .HasColumnType("bit");

                    b.Property<bool>("ptype")
                        .HasColumnType("bit");

                    b.Property<int>("refno")
                        .HasColumnType("int");

                    b.HasKey("Pcode");

                    b.ToTable("PartnerDetails");
                });

            modelBuilder.Entity("MIS_DEMO.Models.Receipt", b =>
                {
                    b.Property<string>("ReceiptNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("TotalPaidAmt")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ReceiptNo");

                    b.ToTable("RECEIPT");
                });

            modelBuilder.Entity("MIS_DEMO.Models.ReceiptPayInfo", b =>
                {
                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChequeCardNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiptNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("RECEIPT_PAY_INFO");
                });

            modelBuilder.Entity("MIS_DEMO.Models.SalesFact", b =>
                {
                    b.Property<string>("CusCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoDocNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LocShort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pat_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RefDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SalesRepCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesRepName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SoldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SupCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SysDateTime")
                        .HasColumnType("datetime2");

                    b.ToTable("VW_SALES_FACT");
                });

            modelBuilder.Entity("MIS_DEMO.Models.SalesRep", b =>
                {
                    b.Property<string>("SalesRepCode")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("SalesRepCode");

                    b.Property<string>("SalesRepName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SalesRepName");

                    b.HasKey("SalesRepCode");

                    b.ToTable("SALES_REP");
                });

            modelBuilder.Entity("MIS_DEMO.Models.StockTeamValue", b =>
                {
                    b.Property<int?>("AgingDays")
                        .HasColumnType("int");

                    b.Property<string>("BatchNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BatchNo");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ExpiryDays")
                        .HasColumnType("int");

                    b.Property<string>("ItemID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemRefNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ShipmentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ShipmentDate");

                    b.Property<decimal>("StockQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("StockValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SupCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TeamCode");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TeamName");

                    b.ToTable("VW_STOCK_TEAM_VALUE");
                });

            modelBuilder.Entity("MIS_DEMO.Models.SupplierAsm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ASMCODE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SUPCODE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SUPPLIER_ASM");
                });

            modelBuilder.Entity("MIS_DEMO.Models.TargetMain", b =>
                {
                    b.Property<string>("TranNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Frequence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("MonthlyTarget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusMonth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TranNo");

                    b.ToTable("TARGET_MAIN");
                });

            modelBuilder.Entity("MIS_DEMO.Models.TargetMonthsRepSpecial", b =>
                {
                    b.Property<string>("MonthNameTarget")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MonthNo")
                        .HasColumnType("int");

                    b.Property<string>("SalesRepCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SysDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("TargetActual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("TargetRefNo")
                        .HasColumnType("bigint");

                    b.Property<string>("TranNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserNameAsm")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("TARGET_MONTHS_REP_SPECIAL");
                });

            modelBuilder.Entity("MIS_DEMO.Models.TeamMis", b =>
                {
                    b.Property<string>("LocCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LocName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocShort")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocCode");

                    b.ToTable("TEAM_MIS");
                });

            modelBuilder.Entity("MIS_DEMO.Models.UserRepMap", b =>
                {
                    b.Property<string>("SalesRepCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SalesRepCode");

                    b.Property<string>("TeamCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TeamCode");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Type");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UserName");

                    b.ToTable("WKF_USER_REP_MAP");
                });

            modelBuilder.Entity("MIS_DEMO.Models.Users", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UserName");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmailAddress");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Password");

                    b.HasKey("UserName");

                    b.ToTable("USERS");
                });

            modelBuilder.Entity("MIS_DEMO.Models.VwSalesReturnFact", b =>
                {
                    b.Property<string>("CusCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoDocNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LocShort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pat_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("RefDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ReturnedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RtnDocNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesRepCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesRepName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("VW_SALES_RETURN_FACT");
                });

            modelBuilder.Entity("MIS_DEMO.Models.WKF_MAP_REP_ASM", b =>
                {
                    b.Property<string>("SalesRepCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("WKF_MAP_REP_ASM");
                });

            modelBuilder.Entity("MIS_DEMO.Models.WKF_MAP_SM_ASM", b =>
                {
                    b.Property<string>("UserNameASM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserNameSM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("WKF_MAP_SM_ASM");
                });

            modelBuilder.Entity("MIS_DEMO.Models.WkfMapAsmDir", b =>
                {
                    b.Property<string>("UserNameAsm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserNameDir")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("WKF_MAP_ASM_DIR");
                });

            modelBuilder.Entity("MIS_DEMO.Models.WkfMapRepAsmMis", b =>
                {
                    b.Property<string>("SalesRepCode")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("SalesRepCode");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UserName");

                    b.HasKey("SalesRepCode");

                    b.ToTable("WKF_MAP_REP_ASM_MIS");
                });
#pragma warning restore 612, 618
        }
    }
}
